Add specs for all models
Abe1able/Blog-App pull request #3
Opened 2023-05-05 21:26 UTC by Abe1able

### In this milestone of the project, I added validations to the models and created specs for them

These are the details:
Added the following validations:

**For the User model:** 
> Name must not be blank.
> PostsCounter must be an integer greater than or equal to zero.

**For the Post model:**
> Title must not be blank.
> Title must not exceed 250 characters.
> CommentsCounter must be an integer greater than or equal to zero.
> LikesCounter must be an integer greater than or equal to zero.

**I added unit specs for all the models' methods and validations.**

2023-05-05 21:36 UTC, KDlamini commented
## Status: Invalid 🔴 

### Hi @Abe1able 🙋‍♀️,  

While you made a great effort in this project, I can't review your code.

## Invalid Code Review Request
 
You have submitted a project that has a README that is not professional. Here are key points to consider when documenting your README.

- All main headers from the [README template](https://github.com/microverseinc/readme-template) should be present. ✖️ 

Kindly add and document the `Acknowledgments` section.
![image](https://user-images.githubusercontent.com/38088818/216764621-55a10d26-d53f-46ce-9dfe-485af2277370.png)


- There should not be any blank sections that do not have content. ✖️ 

Kindly document the `Show your support` section.
![image](https://user-images.githubusercontent.com/38088818/216553663-73255cf6-7c78-4bb4-a924-dbefc6998780.png)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-06 01:17 UTC, franclobo requested changes
Hi @Abe1able, 

# ♻️ Required Changes ♻️

![so-close-jim-halpert](https://user-images.githubusercontent.com/58642949/236590471-2ed10ca9-45d8-47ec-a04d-9f95691da946.gif)

Good job so far!
You are doing it well 👏🏽 there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct Git flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Please 🙏🏽 ensure that all the tests passed 👇🏽 

![image](https://user-images.githubusercontent.com/58642949/236590408-492f321c-f5e7-47bf-80a2-69206d68d42f.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 01:17 UTC, franclobo commented on spec/models/post_spec.rb
> +  end
- [ ] Kindly add this test to validate the maximum number of characters 👇🏽 

> Title must not exceed 250 characters.

2023-05-06 03:26 UTC, Favourezeugwa approved these changes
## STATUS: APPROVED 🥇 🏆 🍹 

Hi @Abe1able ,

I am Favour 👩🏽 , your reviewer for this PR.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Yayyy! 💃🏽, Congratulations! 🎉 🎉🎉


## Highlights 💯 
- No Linter errors ✔️
- `User` and `Post` model has validations ✔️
- Model specs has **Validation** tests ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 20:22 UTC, merged